/**
 * Reads the rendered preview PNGs in `.cache/example-previews/` and writes their intrinsic
 * pixel dimensions to `src/lib/examples/preview-dimensions.ts`. The example pages use these to
 * set `width`/`height` on the preview <img> (prevents layout shift / CLS) and og:image dimensions.
 *
 * Run after `npm run examples:render` (which populates the cache): `npm run examples:dimensions`.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { GALLERY_SLUGS } from './gallery-slugs.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const BITEXT_ROOT = join(__dirname, '..');
const CACHE_DIR = join(BITEXT_ROOT, '.cache', 'example-previews');
const OUT_FILE = join(BITEXT_ROOT, 'src', 'lib', 'examples', 'preview-dimensions.ts');

/** Read width/height from a PNG IHDR chunk (bytes 16–24, big-endian). */
function readPngSize(path: string): { width: number; height: number } {
	const buf = readFileSync(path);
	if (buf.length < 24 || buf.toString('ascii', 12, 16) !== 'IHDR') {
		throw new Error(`Not a PNG with IHDR: ${path}`);
	}
	return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

function main(): void {
	const available = new Set(
		readdirSync(CACHE_DIR)
			.filter((f) => f.endsWith('.png'))
			.map((f) => f.replace(/\.png$/, ''))
	);

	const entries: string[] = [];
	for (const slug of GALLERY_SLUGS) {
		if (!available.has(slug)) {
			throw new Error(`Missing preview PNG for "${slug}" — run \`npm run examples:render\` first.`);
		}
		const { width, height } = readPngSize(join(CACHE_DIR, `${slug}.png`));
		entries.push(`\t'${slug}': { width: ${width}, height: ${height} }`);
	}

	const file = `// Generated by \`npm run examples:dimensions\` from .cache/example-previews/*.png.
// Do not edit by hand — re-run after rendering previews.
export interface PreviewDimensions {
	width: number;
	height: number;
}

export const EXAMPLE_PREVIEW_DIMENSIONS: Record<string, PreviewDimensions> = {
${entries.join(',\n')}
};
`;
	writeFileSync(OUT_FILE, file);
	console.log(`Wrote ${GALLERY_SLUGS.length} dimensions to ${OUT_FILE}`);
}

main();
